### ISSUE TITLE
Is first lab and discussion due date correct?

### ISSUE THREAD

**Issue by JasonSills** [DS4PS/cpp-526-spr-2020#1]
Hi,

I'm double checking that the assignment due dates for the discussion and lab 1 are correct. The syllabus states that both are due January 13th, the first day of class. Is this correct? Thank you!

**Comment by jamisoncrawford** [comment]
@JasonSills Hi Jason, we're currently in the process of updating the course shell with new due dates. In the meantime, just familiarize yourself with the course and textbook contents. I'll have at least one introductory video uploaded by the end of the weekend that should provide a bit more context.
