### ISSUE TITLE
Lab 2: Single Family Home

### ISSUE THREAD

**Issue by babsr** [DS4PS/cpp-526-spr-2020#12]
I'm trying to do the question, "How many Single Family homes are in Syracuse? Map your results." I have followed the code that is on the lab instructions. When I run the code it is printing out Warning messages. 

Here is my code:
`singleFamily <- dat$land_use == "Single Family"

sum(singleFamily)

group.colors <- ifelse( singleFamily, "firebrick", "gray80")
plot( dat, border=NA, col=group.colors, 
       main= 'land_use == "Single Family"', cex.main=2.5)
`
The errors that I am receiving are as follows:

![image](https://user-images.githubusercontent.com/59803514/73144915-dc500280-406f-11ea-80b0-c64eb9f80f81.png)

**Comment by babsr** [comment]
Saw that this wasn't needed.

**Comment by lecy** [comment]
Yes, please skip that example please. Start with the downtown data. 

Note that you need the spatial map packages loaded before you can plot the data:

```
library( geojsonio )
library( sp )
library( rgdal )
```

Load the map file:

```{
URL <- "https://raw.githubusercontent.com/DS4PS/Data-Science-Class/master/DATA/downtown-syr.geojson"
downtown <- geojson_read( URL, what="sp" )
plot( downtown,  border="gray50", col="gray80" )
```

**Comment by jamisoncrawford** [comment]
@babsr one more little potential pitfall - the variable name in the .geojson data is `landuse` while the variable name in the parcel data is `land_use`!

**Comment by lecy** [comment]
just fixed that in q1 instructions! thanks for the catch

**Comment by jamisoncrawford** [comment]
@lecy sure thing!
