### ISSUE TITLE
Yellowdig Access

### ISSUE THREAD

**Issue by karen-liz** [DS4PS/cpp-526-spr-2020#3]
Hi! I'm trying to access the Yellowdig for the "Introduce Yourself" assignment but continue to receive the Canvas page pictured below. Anyone having the same issue or know how to fix it? I also tried emailing the professor but the hyperlink on the syllabus doesn't seem to currently work. Please let me know if I am missing something.

![Screen Shot 2020-01-13 at 12 59 16 PM](https://user-images.githubusercontent.com/59844459/72287593-8e191900-3604-11ea-9c5a-f3eba18d678d.png)

Thanks!
Karen

**Comment by lecy** [comment]
Karen - the YellowDig tab had not yet been published in Canvas. Just updated the setting - see if that works please.

**Comment by karen-liz** [comment]
It seems to be working now. Thank you!
